name: battflow_env
channels:
  - conda-forge
dependencies:
  - acpype
  - pip:
    - GromacsWrapper==0.9.1
    - mdanalysis==2.9.0
    - mdapackmol==0.1.0
    - pymongo==4.13.0
    - PyYAML==6.0.2
    - ase==3.25.0
    - cclib==1.8.1
