mongodb:
    host : localhost
    port : 27017
    database : working_db
    collection : working_collection

md_run_env:
    mdrun : "gmx mdrun" # The command for the execution of GROMACS in the HPC
    mpiexec : "" # complete path to call the executer of the HPC (use e.g "which srun" to find out")
    ncores : 8 # Total number of cores used in the mpi md simulation to facilitate GromacsWrapper to identify everything in different HPCs
    
md_simulations:
    li_itp : resources/md_topologies/li.itp
    k_itp : resources/md_topologies/k.itp
    ca_itp : resources/md_topologies/ca.itp
    na_itp : resources/md_topologies/na.itp
    zn_itp : resources/md_topologies/zn.itp
    cl_itp : resources/md_topologies/cl.itp    
    li_pdb : resources/md_topologies/li.pdb
    k_pdb : resources/md_topologies/k.pdb
    ca_pdb : resources/md_topologies/ca.pdb
    na_pdb : resources/md_topologies/na.pdb
    zn_pdb : resources/md_topologies/zn.pdb
    cl_pdb : resources/md_topologies/cl.pdb
    topol_main : resources/md_topologies/topol_gaff2.top
    
dft_simulations:
    orca_profile : /usr/local/orca_5.0.3/orca
    orca_input_block : "B3LYP 6-311+G(d,p)"
    ncores : 8
    li_energy : -203.567718
    
    